[package]
name = "bevy_gameplay_tag"
version = "0.2.0"
edition = "2024"
authors = ["SuitedRioter"]
description = "A flexible gameplay tag system for Bevy, inspired by Unreal Engine's Gameplay Tags"
license = "MIT"
repository = "https://github.com/SuitedRioter/bevy_gameplay_tag"
homepage = "https://github.com/SuitedRioter/bevy_gameplay_tag"
documentation = "https://docs.rs/bevy_gameplay_tag"
readme = "README.md"
keywords = ["bevy", "gamedev", "gameplay", "tags", "ecs"]
categories = ["game-development", "game-engines"]

[dependencies]
bevy = "0.18.1"
string_cache = "0.9"
serde_json = "1.0.149"
serde = "1.0.228"

[dev-dependencies]
bevy-inspector-egui = "0.36.0"
